contact_links:
  - name: ⚠️ Extension/source issue
    url: https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose
    about: Issues and requests for extensions and sources should be opened in the tachiyomi-extensions repository instead
