name: Generate changelog

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag of the latest release
        required: true

permissions:
  contents: write

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v2
        with:
          config: .github/workflows/cliff.toml
          args: -t "${{ github.event.inputs.tag }}"
        env:
          OUTPUT: CHANGELOG.md
      
      - name: Push changelog
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add CHANGELOG.md
          git commit -m "chore(changelog): Update changelog"
          git push
