name: CI Publish

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v2
        id: git-cliff
        with:
          config: .github/workflows/cliff.toml
          args: -vv --latest 
        env:
          OUTPUT: CHANGELOG.md

  build:
    name: Build artifacts and create draft release
    needs: changelog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt

      - name: Copy CI gradle.properties
        run: |
          mkdir -p ~/.gradle
          cp .github/runner-files/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Build project
        uses: gradle/gradle-command-action@v2
        with:
          arguments: :server:shadowJar

      - name: Move files
        run: |
          mv server/build/aniyomi-extensions-tester-v*.jar anitester.jar
          # mv server/build/min/aniyomi-extensions-tester-v*.jar anitester-min.jar

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Aniyomi-extensions-tester ${{ github.ref_name }}
          body: ${{ needs.changelog.outputs.release_body }}
          # anitester-min.jar
          files: |
              anitester.jar
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
